### ISSUE TITLE
task2

### ISSUE THREAD

**Issue by Mohamedmotamed** [Mohamedmotamed/ASUMobiCarG46#4]
2-search for the best tracker for our pro "ir sensor"    "mohamed khaled+mahmoud mohamed+ motamed +yara+yahia+mahmoud ramzy""  deadline 3/4 11.59 pm

**Comment by motamed** [comment]
I think am in the wrong place

**Comment by MohamedKhaled30** [comment]
انا من رئيي ان ال
 Line Tracker Module (3 Channels)
 مش بيبقي دقيق اوي علشان المساحة اللي هيغطيها مش هنعرف نتحكم فيها بحكم انها ثابته علي الموديول 
3 Line Tracker فشايف ان الانسب اننا نستخدم 
و نظبط اماكنهم بحيث يطلعلنا الدقة عالية والسعر اقل لاننا معانا واحد فهنجيب اتنين بس 
و اللي انتو شايفينه برده

**Comment by yara-alaa** [comment]
replied committing a text called (task 2)sensor predicted to achieve the task with high performance in issues replies folder and a code called 2nd_task_using_lsa08 in Project codes folder .
