### ISSUE TITLE
the best way to charge the battries

### ISSUE THREAD

**Issue by mohamedabdallah43** [Mohamedmotamed/ASUMobiCarG46#5]

**Comment by mohamedabdallah43** [comment]
![29829591_1294093657401579_504916637_o](https://user-images.githubusercontent.com/36481681/38151123-cc596220-3416-11e8-98f7-adb9e937b301.jpg)

**Comment by mohamedabdallah43** [comment]
دي كدا هنعدل على البيز اللي هنجيبها وهنخليها بالشكل دا وهنستخدم السويتشات دي بحيث عند الشحن بالسويتشات دي هتخلي كل البطاريات توازي عشان نقدر نشحن بالتي بي 4056 واثناء تشغيلنا للعربية هنبقي شغالين بالتوصيلة اللي هي اتنين توازي توالي مع اتنين توازي تاني وهنبقي فاتحين سويتشات البارليل

**Comment by Mahmoud3072** [comment]
ايه فايده الاتنين سويتش اللى تحت ماممكن نوصلهم على التي بي على طول وكده كده مش هيوصلهم تيار

**Comment by mohamedabdallah43** [comment]
هيبقي كدا عندك مسارين، بمعنى اني لما هوصلهم عع التي بي ما هي هوصلها ف حديد يعني موصل يعني هتلمسلي السالبين مع بعض ع طول والموجبين مع بعض ع طول وانا مش عاوز اخلي البطاريات بارليل ع طول ففايدته اني بفتحهم لما بستخدم المسار التاني وصلت؟

**Comment by Mahmoud3072** [comment]
اه تمام عاش
